### ISSUE TITLE
Foreign keys reference to previous generated records if run fixtures for more than 1 time

### ISSUE THREAD

**Issue by taurencoder** [city41/node-sql-fixtures#22]
I'm not sure if this is a valid bug but I'm running into this issue when I tried to run my fixtures multiple times. Here's my data spec:
```
products: [{
    'name': 'Mock product 01',
    'price': 100
  }, {
    'name': 'Mock product 02',
    'price': 200
  }],
productSettings: [{
    'product_id': 'products:0'
  }, {
    'product_id': 'products:1'
}]
```
After run this fixture for 2 times, there're actually 4 products in database which have separate id 1,2,3,4. I also get 4 ProductSettings records, but their foreign keys are all pointing to product_id 1 or 2. The other two id (3&4) are never referenced.

I tried to call destroy() method after fixture is persistent to database but it doesn't help, @city41 do you have any idea about this?

**Comment by city41** [comment]
hmmm, interesting. This feels like it might be a bug. Can you also post how you are calling into sqlFixtures? If you have a small repro that shows what's happening that'd be awesome.

**Comment by taurencoder** [comment]
@city41 , I've created a repo to reproduce this issue: https://github.com/taurencoder/sql-fixtures-issue

**Comment by city41** [comment]
Thanks for the great repro. I know what the issue is, and it's because sql-fixtures flubbed a little bit in regards to mysql.

When inserting with mysql, it does not return the result of the insert. Instead you can query `LAST_INSERT_ID()` to get the id of the last row that was inserted. postgres returns all of the inserted rows directly.

So [here](https://github.com/city41/node-sql-fixtures/blob/master/lib/insert-records.js#L91), sql-fixtures is cheating with mysql a little bit. What it really needs to do is insert each row one at a time, then get that row with `LAST_INSERT_ID()`

This is definitely fixable. I'll have some time to look at it this weekend.

**Comment by city41** [comment]
Actually, I found a simpler fix @taurencoder. You should find version `0.8.1` fixes the issue. I added a [test](https://github.com/city41/node-sql-fixtures/blob/master/test/integration/integration-specs.js#L258) for your scenario.

Technically this fix is still a bit of a flub. MySQL just isn't very helpful with inserts. I think there are probably still some use cases out there where MySQL will still fail. But this is an improvement, and I'll look into a more robust solution longterm.

**Comment by city41** [comment]
The more I think about it, the fix in `0.8.1` can fail in ways that using `LAST_INSERT_ID()` won't. So it is still worth it to implement that version of the fix.

@taurencoder you should still find `0.8.1` helps you. Let me know if it doesn't.

**Comment by taurencoder** [comment]
Thanks for the explanation and quick fix, I tried `0.8.1` but the references are still incorrect when there're multiple records inserted, somehow the first row is right BTW.
```
"id","quantity","product_id"
1,10,1
2,20,2
3,10,3
4,20,2
5,10,5
6,20,2
7,10,7
8,20,2
```

**Comment by city41** [comment]
Darn, I was hoping that'd work. I'll tackle the real solution this weekend.

-----Original Message-----

**Comment by city41** [comment]
@taurencoder I implemented the more robust solution, it is in `0.8.2`. I also improved the test to more closely match your scenario.

I'm pretty sure this one should help you now. But the truth is this fix is still a little leaky. If you still run into problems let me know, I may have to really rethink things if so.

**Comment by taurencoder** [comment]
Thanks @city41 , this version does fixed my issue. Appreciate your quick response :)

**Comment by city41** [comment]
excellent, thanks for testing it out
