### ISSUE TITLE
Pass existing knex object to sql-fixtures

### ISSUE THREAD

**Issue by dcrockwell** [city41/node-sql-fixtures#25]
Is there a way to use an existing knex object so as to avoid creating multiple connections in a test?

**Comment by city41** [comment]
Currently the best way to do that is to create an instance of sqlFixtures then keep that instance around. That will just use one knex for the life of the instance. There isn't any way to use an existing knex instance, but that shouldn't be hard to add.

-----Original Message-----

**Comment by dcrockwell** [comment]
The issue is that we use knex in our tests, and sqlfixtures. This causes two connections to the database instead of one because sqlfixtures can't share the connection pool of the test's knex instance.

I've forked the repo. I'll submit a PR some time this week.

**Comment by city41** [comment]
hey @dcrockwell any progress on this? if not, I can take a stab at it. Just don't want to trample over any work you've done.

**Comment by dcrockwell** [comment]
I'm afraid not. Please, go ahead.

**Comment by city41** [comment]
This is now implemented in `0.11.0`, and documentation is [here](http://city41.github.io/node-sql-fixtures/#using-an-existing-knex-instance). Please let me know if you hit any issues with this @dcrockwell
