### ISSUE TITLE
Insert a stringified JSON cause error

### ISSUE THREAD

**Issue by zation** [city41/node-sql-fixtures#26]
When I create a fixture like:

```js
{
	test: '{test: 1}'
}
```

I will get error: `Unhandled rejection Error: Non-existant dependency. Remaining needs: {test: 1}`

Can you please let me know if we not support to insert a string which look like a JSON?

**Comment by city41** [comment]
Currently the way to do that is to double up the colon

```
{
    test: '{test:: 1}'
}
```

I want to change it so you escape the colon, ie `{test\: 1}`, but that isn't implemented yet.

**Comment by zation** [comment]
Today our team member @taurencoder tried
```js
{
    test: '{test: 1}'
}
```
With my folk, but he found mysql will escape `{` and `}`... So I guess both my PR and `{test\: 1}` will not work. We may need to use
```js
{
        test: '"{\"test\": 1}"'
}
```
to work around

**Comment by taurencoder** [comment]
@zation I tried @city41's suggestion and double colons works eventually. 

Also the missing `{` and `}` is not an issue of mysql escaping but perhaps the changes on your forked branch.

**Comment by city41** [comment]
@taurencoder what do you mean by "eventually"? Does doubling up the colons work ok with the main current release?

**Comment by zation** [comment]
@city41 He means it works perfectly

**Comment by taurencoder** [comment]
@city41 pity for my English, used wrong word. Your main release works good. :)

**Comment by city41** [comment]
@taurencoder @zation that is good to hear. I still want to make this better when I get some free time. But I'm going to close it for now, as `::` does get the job done.

**Comment by ChrisWphoto** [comment]
Just FYI for anyone that may have ended up here searching for `Error: Non-existant dependency. Remaining needs:`

make sure you don't have any colons in your string. for example I had 
`special_instructions: '<p>AC: 30%</p>',`
which was throwing the error. 

Removing the colon `special_instructions: '<p>AC 30%</p>',` fixed the error

**Comment by city41** [comment]
@ChrisWphoto you can double up the colon to escape it, so `special_instructions: '<p>AC:: 30%</p>'` should work. If it doesn't please let me know.

I realize that is an unusual approach to escaping, but that's how sql-fixtures works today. Going with `\` for escaping is something I always wanted to do but haven't gotten around to.
