### ISSUE TITLE
primary key warning can show for postgres

### ISSUE THREAD

**Issue by city41** [city41/node-sql-fixtures#29]
@shunjikonishi has reported seeing the primary key warning when using postgres, which should not be happening. Here is a [gist](https://gist.github.com/shunjikonishi/2db1bde3286b1bc548f2) repro'ing the issue.

I am looking into this now.

**Comment by city41** [comment]
This is now fixed with `0.10.1`. 

@shunjikonishi  please let me know if you still see the warning, don't forget to undo `showWarning: false`

**Comment by shunjikonishi** [comment]
@city41 

I tested with 0.10.1.
Warning was disappear.

Thanks
