### ISSUE TITLE
Blows up if ":" exists in value

### ISSUE THREAD

**Issue by cbrunnkvist** [city41/node-sql-fixtures#37]
I had one particular problem where I was loading a snippet of JSON to use as an archetype for a rather large row. Since some if the columns it contained are SQL dates, they of course looks like strings, which of course got me into trouble since timestamps like "10:24:25" makes sql-fixtures look for a table called "10" ...

I wonder if it would be possible/a better idea to resolve all known table keys, and then if we see a reference we don't know about, simply leave the value as-is?

**Comment by city41** [comment]
The current solution is to double up the colons, ie "10::24::25". sql-fixtures treats double colons as single literal colons. Leaving an unknown value as is could mean it's a typo and intended to be a relation.

What about something like

```
var spec = {
  myTable: {
    myTimestampColumn: {
      literal: true,
      value: '10:24:25'
    }
  }
};
```

That's pretty verbose though.

**Comment by city41** [comment]
I've decided to not change this, at least for now. I feel the disadvantage of not reporting typos are worse than dealing with lots of literals.
