### ISSUE TITLE
http://

### ISSUE THREAD

**Issue by jney** [city41/node-sql-fixtures#39]
urls (`http://`) are treated as dependencies. how to avoid this ?

**Comment by redorb8** [comment]
I have the same problem... as I am just using this package for unit testing, I left off http (or https as the case may be) and it stopped thinking these values were dependencies. Though it would be nice if this were fixed.

**Comment by redorb8** [comment]
Ah, @jney  I just realized that you have to escape the colon (`http:://`) then it will not give the error about the dependancy. They actually mention this in their documentation http://city41.github.io/node-sql-fixtures/#string-values-with-colons-in-them

**Comment by jney** [comment]
thank you @redorb8
